apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-web
  template:
    metadata:
      labels:
        app: devops-web
    spec:
      containers:
      - name: devops-web
        image: chandu22727/devops-website:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5173
